name: Deploy to GitHub Pages

permissions:
  contents: write  # Ensure the bot has write permissions

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4.1.7

      # Set up Node.js environment
      # - name: Set up Node.js
        # uses: actions/setup-node@v4.0.3
        # with:
          # node-version: '20'

      # Install dependencies
      # - name: Install dependencies
        # run: npm install

      # Generate the static files
      # - name: Generate static files
        # run: npm run generate

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public  # The folder to deploy
          publish_branch: gh-pages  # Target branch for deployment
